var CCFrontTask2 = require('./CCFrontTask2.js');

console.log("********************************************");
console.log("------------GENERATE-RUNIC-WORDS------------");
console.log(CCFrontTask2.generateRunicWords());
console.log("--------------------------------------------");
console.log(CCFrontTask2.generateRunicWords(0));
console.log("--------------------------------------------");
console.log(CCFrontTask2.generateRunicWords('Jah-Ith-Ber'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.generateRunicWords(2));
console.log("--------------------------------------------");
console.log(CCFrontTask2.generateRunicWords(6));
console.log("--------------------------------------------");
console.log(CCFrontTask2.generateRunicWords(100));
console.log("--------------------------------------------");

console.log("-------------CHECK-RUNIC-WORDS--------------");
console.log(CCFrontTask2.checkRunicWord('Jah-Ith-Ber'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord('Eld-Lum-Eth-Cham-El-Ko-Lem-Ral-Vex-Ith-Io-Zod-Fal-Thul-Hel-Nef-Ber'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord('Ist'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord('Zod-Jah-Ith-Ber'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord('Jah-Ith-Ber-Jah'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord('Jah-Ith-Ber-Tadaaa'));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord(''));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord());
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord(10));
console.log("--------------------------------------------");
console.log(CCFrontTask2.checkRunicWord(true));
console.log("********************************************");